xvfb-run -a python collect_data_main.py \
    --category Box,Dishwasher,Display,Microwave,Printer,Bench,Keyboard2 \
    --primact_type pushing  \
    --out_dir ../data/AllTrainCat_push_TRAIN \
    --mode train  \
    --target_part_state closed  \
    --start_dist 0.45   \
    --final_dist 0.10   \
    --move_steps 3500   \
    --wait_steps 2000   \
    --num_processes 20  \
    --start_epoch 0    \
    --save_interval 10  \
    --checkType euler \
    --no_gui \
